# Generated by Django 4.2.4 on 2023-10-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100, unique=True)),
                ('user_email', models.CharField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
    ]
