# Generated by Django 4.2.4 on 2023-11-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(unique=True)),
                ('question_type', models.CharField(choices=[('choice', 'Multiple Choice'), ('text', 'Essay'), ('true_false', 'True or False '), ('code', 'Coding Problem'), ('other', 'Other Type')], max_length=20)),
                ('question', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='examtakers',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
