# Generated by Django 4.2.4 on 2023-11-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_choice_exam_alter_examtakers_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='question_id',
        ),
    ]
