# Generated by Django 4.2.4 on 2023-11-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_exam_id_exam_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='question_id',
            new_name='id',
        ),
    ]
