# Generated by Django 4.2.4 on 2023-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_question_id_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_choices',
            field=models.CharField(default='', max_length=500),
        ),
    ]
