# Generated by Django 4.2.4 on 2023-12-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_exam_question_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_email', models.CharField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
